FROM rust:latest AS build

RUN apt update && apt upgrade -y

RUN rustup toolchain install stable

WORKDIR /app

COPY . /app

RUN cargo build --release 

FROM debian:latest

COPY --from=build /app/target/release/gsutil /usr/local/bin/gsutil

CMD ["/usr/local/bin/gsutil"]