# -*- yaml -*-
version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@3
  gcp-cli: circleci/gcp-cli@2.1.0
  terraform: circleci/terraform@3.0.1

jobs:
  build-deploy-arm:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - sixrs-gke/docker-login
      - sixrs-gke/run-release
      - sixrs-gke/build-and-publish:
          docker-file: Dockerfile.armv7
          project-name: gsutil-arm
  build-deploy-amd:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - sixrs-gke/docker-login
      - sixrs-gke/run-release
      - sixrs-gke/build-and-publish:
          docker-file: Dockerfile.amd
          project-name: gsutil-amd

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test-publish:
          context: 6rs-circle
      - build-deploy-amd:
          context: 6rs-circle
